sylius_grid:
    grids:
        loevgaard_sylius_brand_admin_api_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "%loevgaard_sylius_brand.model.brand.class%"
            sorting:
                name: asc
            fields:
                code:
                    type: string
                    label: loevgaard_sylius_brand.ui.code
                    sortable: ~
                name:
                    type: string
                    label: loevgaard_sylius_brand.ui.name
                    sortable: ~
            filters:
                search:
                    type: string
                    options:
                        fields: [code, name]
