# List of generated routes for better navigation:
# loevgaard_sylius_brand_admin_api_brand_image_index
# loevgaard_sylius_brand_admin_api_brand_image_update
# loevgaard_sylius_brand_admin_api_brand_image_show
# loevgaard_sylius_brand_admin_api_brand_image_delete
loevgaard_sylius_brand_admin_api_brand_image:
    resource: |
        path: 'images'
        alias: loevgaard_sylius_brand.brand_image
        section: admin_api
        except: ['bulkDelete']
        grid: loevgaard_sylius_brand_admin_api_brand_image
        form: Loevgaard\SyliusBrandPlugin\Form\Type\BrandImageType
        serialization_version: $version
        vars:
            route:
                parameters:
                    code: $code
    type: sylius.resource_api

loevgaard_sylius_brand_admin_api_brand_image_index_by_type:
    path: /images/by-type/{type}
    methods: [GET]
    defaults:
        _controller: loevgaard_sylius_brand.controller.brand_image::indexAction
        _sylius:
            serialization_version: $version
            section: admin_api
            serialization_groups: [Default]
            repository:
                method: createPaginatorForBrandAndType
                arguments:
                    - expr:notFoundOnNull(service('loevgaard_sylius_brand.repository.brand').findOneByCode($code))
                    - $type

loevgaard_sylius_brand_admin_api_brand_image_create:
    path: /images/
    methods: [POST]
    defaults:
        _controller: loevgaard_sylius_brand.controller.brand_image:createAction
        _sylius:
            serialization_groups: [Default, Detailed]
            serialization_version: $version
            section: admin_api
            form: Loevgaard\SyliusBrandPlugin\Form\Type\BrandImageType
            factory:
                method: createForBrand
                arguments:
                    - expr:notFoundOnNull(service('loevgaard_sylius_brand.repository.brand').findOneByCode($code))
