build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        php:
            version: "7.4"
        variables:
            COMPOSER_MEMORY_LIMIT: -1

filter:
    excluded_paths: [tests/*, spec/*]
