files:
  - source: /src/Resources/translations/messages.en.yml
    translation: /src/Resources/translations/messages.%two_letters_code%.yml
  - source: /src/Resources/translations/validators.en.yml
    translation: /src/Resources/translations/validators.%two_letters_code%.yml
