loevgaard_sylius_brand_admin_brand:
    resource: |
        alias: loevgaard_sylius_brand.brand
        section: admin
        templates: '@SyliusAdmin/shared/crud'
        redirect: update
        grid: loevgaard_sylius_brand_admin_brand
        permission: true
        except: ['show']
        vars:
            all:
                subheader: loevgaard_sylius_brand.ui.brand
                hook_prefix: 'loevgaard_sylius_brand.brand'
            index:
                icon: 'file image outline'
    type: sylius.resource
