loevgaard_sylius_brand_shop:
    resource: "@LoevgaardSyliusBrandPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

loevgaard_sylius_brand_admin:
    resource: "@LoevgaardSyliusBrandPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin
