loevgaard_sylius_brand_admin_ajax_brands_by_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: loevgaard_sylius_brand.controller.brand::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByPhrase
                arguments:
                    phrase: $phrase

loevgaard_sylius_brand_admin_ajax_brand_by_code:
    path: /
    methods: [GET]
    defaults:
        _controller: loevgaard_sylius_brand.controller.brand::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]
